title Git Integration Sequence

Integration->Git: Any changes?
activate Git
Git-->Integration: No
deactivate Git

Developer->Git: Commit change
Integration->Git: Any changes?
activate Git
Git-->Integration: Yes
deactivate Git
activate Integration
Integration->VersionOne: Create ChangeSet
Integration->VersionOne: Relate ChangeSet to WorkItems
Integration->VersionOne: Link to Git
deactivate Integration

Integration->Git: Any changes?
activate Git
Git-->Integration: No
deactivate Git